### ISSUE TITLE
How does variable scoping work?

### ISSUE THREAD

**Issue by lunelson** [sass/language#30]
Concerning [@content Arguments: Draft 1](https://github.com/sass/language/blob/master/proposal/content-args.md), initial questions / observations.

Firstly @nex3, thanks for moving this forward. 

So as I understand it, the shape this feature is taking is that the `@content` directive can be thought of as a callback function, and the `@include` with `using` syntax as a function-with-callback invocation pattern, more or less.

In my own work I use the 'hack' approach to providing values to `@content` blocks (setting and unsetting a global variable before/after the `@content` directive, respectively) quite extensively, and I'm curious whether this proposed official pattern will support the same use-cases.

For example in the hacked approach, code inside the block of a `@content`-accepting mixin can make reference to 'globally toggled' variables as I described above transparently, without needing to declare them in any way nor explicitly pass them to functions, and may also make use of other functions or mixins (including ones that pass their `@content` on to other `@content`-accepting mixins) that refer to those globals. This becomes like a kind of temporary 'block scope'.

In the proposed syntax however, I am wondering if the 'callback-style' nature means that variables need to be declared (with `using`) and explicitly passed to any functions, or if there is a way to make things a bit more like the effects I describe above. Implicitly I guess this is also a question about how global vs local (block) scopes play out in the proposed syntax pattern.

For example, in the following code what would the output be?

```scss
$bar: 'bar';

@mixin bar-content { @content($bar); }

@mixin bar-setter($foo) {
  $bar: $foo + 'bar';
  @include bar-content using ($bar) {
    @content;
  }
}

@function bar-getter { @return $bar; }

.test {
  @include bar-setter('baz') {
    bar: bar-getter();
  }
}
```

**Comment by nex3** [comment]
This kind of dynamic scoping will not be supported by `@content` arguments; they will be [lexically scoped](https://en.wikipedia.org/wiki/Scope_(computer_science)#Lexical_scoping), just like mixin and function arguments today. And you hit on why: dynamically-scoped variables aren't explicit. We want to make it clear to the reader where every variable comes from, and limit the set of situations where it's possible to introduce a variable to scope implicitly. Of course, you'll still be able to manually fake dynamic scope with global variables as you are today.

The output of your code sample would be

```css
.test {
  bar: "bar"
}
```

The `$bar` assignment in `bar-setter` creates a local variable named `$bar` that shadows the global variable, and the `$bar` reference in `bar-getter` refers to the global `$bar` variable. Writing `using ($bar)` without referring to `$bar` in the content block basically doesn't do anything.

Let me know if that answers your questions!
