### ISSUE TITLE
Map `filter` and `map` functions

### ISSUE THREAD

**Issue by damienwebdev** [sass/language#57]
# Proposal

Add common "functional" functions to iterable objects SASS. 
There are several functions of this class that could be added and would provide significant benefit. E.g.

- [ ] `map`
- [ ] `filter`
- [ ] `reduce`

## Use Case
When writing sass, I find that I spend a significant amount of time writing things that look like:

```scss
$map: (test: 100, test: 200);
$newMap: ();
@each $key, $value in $map {
    $newMap: map-merge(
        $newMap, 
        ($key: (someFunction($value)))
    );
}
```

This common structure is often known as "map" in many functional languages. 

In an ideal world I'd write something like:

```scss
$map: (test: 100, test: 200);
@function mapFunction ($key, $value){
 @return ($key: someFunction($value));
}
$newMap: map($map, mapFunction);
```

## Side notes
There are some odd language semantics here (lambdas), that I've not yet seen in SASS, but may be possible (first class functions).

Additionally, if SASS could support anonymous lambdas (probably difficult), that may also be cool.

### Edge cases
There's also probably some edge cases around providing values that are not args to the callback as values inside the callback function.
